Online_Movie_Store/moviestoreproject/movieapp/urls.py
from django.urls import path
from.import views
app_name='movieapp'
urlpatterns = [

    path('',views.allMovCat,name='allMovCat'),
    path('<int:c_id>/',views.allMovCat,name='movie_by_category'),
    path('<int:c_id>/<str:m_id>/',views.MovieDetail,name='movieCatDeatil'),
    path('add/', views.add_movie, name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),

]

Online_Movie_Store/moviestoreproject/moviestoreproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),
    path('signup/', include('signup.urls')),
    path('searchapp/',include('searchapp.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Online_Movie_Store/moviestoreproject/searchapp/urls.py
from django.urls import path
from . import views

app_name='searchapp'
urlpatterns = [
    path('',views.SearchResult,name='SearchResult'),
]

Online_Movie_Store/moviestoreproject/signup/urls.py
from django.urls import path
from.import views
urlpatterns = [

    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout')

]

Online_Movie_Store/moviestoreproject/signup/models.py
from django.db import models

# Create your models here.

Online_Movie_Store/moviestoreproject/signup/views.py
from django.contrib import messages,auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect



def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            messages.info(request, 'invalid login')
    else:
        return render(request, 'login.html')
# Create your views here.
def register(request):
    if request.method=='POST':
        username=request.POST['username']
        Firstname=request.POST['First_name']
        Lastname=request.POST['Last_name']
        email=request.POST['emailid']
        password=request.POST['password']
        cpassword=request.POST['password1']
        if password==cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request,"Username taken")
                return redirect('register')

            elif User.objects.filter(email=email).exists():
                messages.info(request,"email taken")
                return redirect('register')
            else:
                user = User.objects.create_user(username=username, first_name=Firstname, last_name=Lastname, email=email,
                                                password=password)
                user.save()
                print("user registered")
                return redirect('login')

        else:
            messages.info(request,"password not match")
            return redirect('register')
        return redirect('/')
    else:
        return render(request,"signup.html")
def logout(request):
    auth.logout(request)
    return redirect('/')

Online_Movie_Store/moviestoreproject/templates/add_movie.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<style>
h1{
            text-align:center;

            }
        .row{
            display:flex;
            justify-content:center;
            }



</style>
<body style="background-color:black; color:white;">
 <h1>Add New Movie</h1>
 <div class="row">
      <form method="post" enctype="multipart/form-data" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>

 </div>

</body>
</html>

Online_Movie_Store/moviestoreproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/custom.css' %}" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Poppins&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
        <script src="https://kit.fontawesome.com/5b2caef95b.js" crossorigin="anonymous"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body style="background-color:black; color:white;">
<div class="container-fluid cart_body">
  {% include 'header.html' %}
  {% include 'navbar.html' %}
  {% block content %}
  {% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>
</body>
</html>

Online_Movie_Store/moviestoreproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  {% if category %}
    {{category.description|truncatewords:155}}
  {% else %}
    Welcome to Come Soon Movie recommendation website...
  {% endif %}
{% endblock %}
{% block title %}
  {%if category %}
    {{category.name}}--Coming Soon
  {% else %}
    see our movie collection
  {% endif %}
{% endblock %}
{% block content %}
{% if category %}
<div>
  <div class="row my_row_class">
    <div class="mx_auto">
      <p><a href="{% url 'movieapp:allMovCat' %}"> Movie Collections </a></p>
      </div>
  </div>
</div>
{% endif %}
<div class="mx_auto">
  {% if category %}
  <h1 class="text-center my_title">{{category.name}}</h1>
</div>
  {% else %}
<div>
    <center><img class="my_image my_image_padding" src="{% static 'img/filmcity.png' %}" alt="our movies" width="1450" height="300"></center>
</div>
<br>
<div>
  <h1 class="text-center my_title"> Movie collections</h1>

</div>
{% endif %}
<div class="container">
   <div class="row mx-auto">
    {% for movie in movies.object_list %}
    <div class="container my_bottom_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4">
      <div class="card text-center" style="min-width:18rem;">
      <a href="{{movie.get_url}}">
          {% if movie.image %}
          <img class="card-img-top my_image" src="{{movie.image.url}}"alt="{{movie.name}}">
           {% else %}
          <img class="card-img-top my_image" src="{% static 'path_to_default_image.jpg' %}" alt="{{ movie.name }}">
            {% endif %}
          </a>
    <div class="card-body">
      <h4>{{movie.name}}</h4>
      <p>{{movie.language}}</p>
    </div>
    </div>
    </div>
     {% endfor %}
  </div>
    <div class="mx-auto pb-5">
        {% if movies.paginator.num_pages > 1 %}

        <hr>
        <div class="text-center">
            {% for pg in movies.paginator.page_range %}
                <a href="?page={{pg}}" class="btn btn-light btn-sm {% if movies.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>

{% endblock %}

Online_Movie_Store/moviestoreproject/templates/delete.html
<form method="post">
    {% csrf_token %}
Are you want to delete?
    <input type="submit">

</form>

Online_Movie_Store/moviestoreproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
  <p class="text-center">&copy; Film city, Arthanakk.All righ reserved</p>
</div>

Online_Movie_Store/moviestoreproject/templates/header.html
{% load static %}
<header>
<!--    <center>-->
<!--    <a href=""><img src="{% static 'img/logo.png' %}" alt="logoimage" width="150px;" height="150px;"></a>-->
<!--    </center>-->
</header>

Online_Movie_Store/moviestoreproject/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<style>
        body{
          background-color:black;
          color:white;
            }

         h1{
            text-align:center;

            }
        .row{
            display:flex;
            justify-content:center;
            }

    </style>
</head>
<body>
<h1>Login</h1>
<div class="row">
<form action="login" method="post" >
    {% csrf_token %}
    <table >
        <tr>
            <td> <label>Username</label></td>
            <td> <input type="text" name="username" placeholder="Enter UserName"><br></td>
        </tr>

        <tr>
            <td><label>Password</label></td>
            <td><input type="password" name="password" placeholder="Enter Password"><br> </td>
        </tr>

        <tr>
            <td colspan="2" style="text-align:center;"> <button style="background-color:IndianRed;color:white;">Login</button></td>
        </tr>

 </table>
</form>
</div>
</body>
</html>

Online_Movie_Store/moviestoreproject/templates/movie.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

    {{movie.description|truncatewords:155}}


{% endblock %}
{% block title %}
  {%if category %}
    {{movie.name}}--Coming Soon
  {% endif %}
{% endblock %}
{% block content %}
<div class="row my_pro_row_class">
  <div class="mx_auto">
    <p><a href="{% url 'movieapp:allMovCat' %}">Home</a>|<a href="{{movie.categoty.get_url}}">{{movie.category}}</a>|{{movie.name}}</p>
  </div>
</div>
<div class="container pb-5">
<br>
<div class="row">
  <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
    <div style="min-width:18rem;">
       <img src="{{movie.image.url}}" alt="{{movie.name}}" width="350;" height="350;" >
    </div>
  </div>
    <div class="col-12 col-sm-12  col-md-12 col-lg-6">
        <h1>{{movie.name}}</h1>
      <p >Language : {{movie.language}} </p>
        <p>Genre : {{movie.category}}  </p>
        <p>Release Date: {{movie.release_date}}</p>
        <h3>Story Line</h3>
      <p class="text-justify ">{{movie.description}}</p>
        <p>Main Cast : {{movie.actor}}</p>

       <p><a href="{{ movie.trailer }}" target="_blank">Watch Trailer</a></p>
      <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">Update</a>
        <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
    </div>
  </div>
  <h2>Reviews for {{movie.name}}</h2>
  {% for review in reviews %}
  <div>
     <p>By :{{ review.created_by }}</p>
    <p><i class="fa-regular fa-star"></i>{{ review.rating }}/5 Rating</p>
    <p>{{ review.comment }}</p>

  </div>
{% endfor %}

<!-- Add the review form here as well -->
  <h1>Add Review and Rating</h1>
<form method="post" action="{% url 'movieapp:movieCatDeatil' c_id=c_id m_id=m_id%}">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Submit Review</button>
</form>
</div>

{% endblock %}

Online_Movie_Store/moviestoreproject/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-dark">
  <div class="container-fluid">
     <a href="{% url 'movieapp:allMovCat' %}"><img src="{% static 'img/filmcitylogo.png' %}" alt="logoimage" width="50px;" height="50px;"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active text-white" aria-current="page" href="{% url 'movieapp:allMovCat' %}">Home</a>
        </li>
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" href="#">Link</a>-->
<!--        </li>-->
        <li class="nav-item dropdown {% if 'movieapp' in request.path %}active{% endif %}">
          <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Category
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{%url 'movieapp:allMovCat' %}">All Movies</a></li>
             {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}
          </ul>
        </li>

        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link text-white">Hello! {{user.first_name}}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="signup/logout">Logout</a>
        </li>
        <li class="nav-item">

          <a class="nav-link text-white" aria-disabled="true" href="add/">AddMovie</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link text-white" href="signup/register">Signup</a>
        </li>

        <li class="nav-item">
          <a class="nav-link text-white" href="signup/login">Login</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'searchapp:SearchResult' %} " method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
      </form>
    </div>
  </div>
</nav>

Online_Movie_Store/moviestoreproject/templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {{ movie.description|truncatewords:155 }}
{% endblock %}

{% block title %}
  {% if category %}
    {{ movie.name }}
  {% endif %}
{% endblock %}

{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for: <b>"{{query}}"</b></p>
</div>
<div class="container">
   <div class="row mx-auto pb-5">
        {% for movie in movies %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4 p-3">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{ movie.get_url }}"><img class="card-img-top my_image" height="250px;" src="{{ movie.image.url }}" alt="{{ movie.name }}"></a>
                <div class="card-body">
                    <h4>{{ movie.name }}</h4>
                    <p>{{movie.language}}</p>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text">0 results found</p>
        </div>
    {% endfor %}
   </div>
</div>
{% endblock %}

Online_Movie_Store/moviestoreproject/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<style>
body{
          background-color:black;
          color:white;
            }
 h1{
            text-align:center;

            }
        .row{
            display:flex;
            justify-content:center;
            }

</style>
<h1>Registration From</h1>
<div class="row">


<form action="register" method="post" >
    {% csrf_token %}
    <table >
        <tr>
            <td> <label>Username</label></td>
            <td> <input type="text" name="username" placeholder="Enter UserName"><br></td>
        </tr>
         <tr>
            <td> <label>First_name</label></td>
            <td> <input type="text" name="First_name" placeholder="Enter firstName"><br></td>
        </tr>
         <tr>
            <td> <label>Last_name</label></td>
            <td> <input type="text" name="Last_name" placeholder="Enter lastName"><br></td>
        </tr>


        <tr>
            <td><label>Email_ID</label></td>
            <td><input type="email" name="emailid" placeholder="Enter email id"><br></td>
        </tr>

        <tr>
            <td><label>Password</label></td>
            <td><input type="password" name="password" placeholder="Enter Password"><br> </td>
        </tr>
        <tr>
            <td><label>Confirm Password</label></td>
            <td><input type="password" name="password1" placeholder="confirm Password"><br></td>
        </tr>
        <tr>
            <td colspan="2" style="text-align:center;"> <button style="background-color:darkblue;color:white;">Submit</button></td>
        </tr>

 </table>
</form>
    </div>

 <div style="text-align:center">
     {% for msg in messages %}
            <h4>{{msg}}</h4>
     {% endfor %}
</div>


</body>
</html>

Online_Movie_Store/moviestoreproject/templates/update.html
<style>
body{
          background-color:black;
          color:white;
            }
 h1{
            text-align:center;

            }
        .row{
            display:flex;
            justify-content:center;
            }

</style>
<h1>Update Movie {{movie.name}}</h1>
<div class="row">
 <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">

</form>
</div>